"""
procurement_monitoring_engine.py
---------------------------------
PSE-7A — Executive Monitoring & Early Warning System.

Consumes outputs from PSE-5A (ScenarioReport) and PSE-5B (ExecutiveReport)
to generate proactive alerts and an executive watchlist.

Purpose: not to make procurement decisions, but to answer
    "What should management pay attention to next?"

Does NOT recalculate procurement quantities.
Does NOT modify scenario logic or forecasting logic.
Reads production constants (ROP, safety stock, mix targets) as read-only
thresholds — no formulas are duplicated or overridden.

Public API
----------
    generate_monitoring_report(exec_report_dict, scenario_report_dict,
                               local_inventory_tons, imported_inventory_tons,
                               total_inventory_tons, today, ...)
        → ExecutiveMonitoringReport

    run_pse7a(workbook_path, ...)
        → ExecutiveMonitoringReport
"""
from __future__ import annotations

import sys
from dataclasses import dataclass, asdict
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent))

# Read-only constants from approved production engine — not recalculated here.
from procurement_strategy_engine import (
    DAILY_CONSUMPTION_LOCAL,
    DAILY_CONSUMPTION_IMPORTED,
    DAILY_CONSUMPTION_TOTAL,
    LOCAL_ROP_TONS,
    IMPORTED_ROP_TONS,
    SAFETY_STOCK_LOCAL_TONS,
    SAFETY_STOCK_IMPORTED_TONS,
    LOCAL_LEAD_TIME_DAYS,
    IMPORTED_LEAD_TIME_DAYS,
    LOCAL_MIX_TARGET,
    IMPORTED_MIX_TARGET,
    MIN_STOCK_DAYS,
    MIX_TOLERANCE_PCT_POINTS,
)
from procurement_planning_engine import PRICE_RISING, PRICE_FALLING, PRICE_NEUTRAL

__all__ = [
    "MonitoringAlert",
    "WatchlistItem",
    "ExecutiveMonitoringReport",
    "generate_monitoring_report",
    "run_pse7a",
]

# ---------------------------------------------------------------------------
# Severity ordering (lower rank = more severe)
# ---------------------------------------------------------------------------
_SEV_RANK = {
    "CRITICAL": 0,
    "HIGH":     1,
    "WARNING":  2,
    "NOTICE":   3,
    "INFO":     4,
}

# ---------------------------------------------------------------------------
# Alert thresholds — tunable without changing any procurement calculations
# ---------------------------------------------------------------------------
_DAYS_TO_ROP_NOTICE   = 45   # days before reaching ROP → NOTICE
_DAYS_TO_ROP_WARNING  = 21   # days before reaching ROP → WARNING
_DAYS_TO_ROP_HIGH     = 10   # days before reaching ROP → HIGH

_SS_BREACH_BUFFER_PCT = 0.20  # fire HIGH when within 20% of safety stock

_MIX_DEV_NOTICE  =  5.0   # percentage-point deviation from mix target
_MIX_DEV_WARNING = 10.0
_MIX_DEV_HIGH    = 15.0

_STORAGE_PCT_INFO    = 0.70
_STORAGE_PCT_NOTICE  = 0.80
_STORAGE_PCT_WARNING = 0.90

_CONF_SCORE_INFO    = 75   # confidence below 75 → INFO
_CONF_SCORE_NOTICE  = 65   # confidence below 65 → NOTICE
_CONF_SCORE_WARNING = 50   # confidence below 50 → WARNING

_PRICE_DELTA_HIGH_VOLATILITY = 20.0   # |delta %| above this → WARNING (volatility)

_COST_INCREASE_NOTICE  =  200_000   # USD cost avoidance threshold → NOTICE
_COST_INCREASE_WARNING =  500_000
_COST_INCREASE_HIGH    = 1_000_000

_SAVING_OPP_INFO    =   50_000   # USD saving opportunity threshold → INFO
_SAVING_OPP_NOTICE  =  100_000
_SAVING_OPP_WARNING =  500_000

_SIM_OUTPERFORM_NOTICE = 8    # score delta points before firing NOTICE
_SIM_OUTPERFORM_HIGH   = 20   # score delta points before firing HIGH


# ===========================================================================
# Output dataclasses
# ===========================================================================

@dataclass
class MonitoringAlert:
    """A single early-warning alert generated by PSE-7A."""
    alert_id: str
    title: str
    severity: str              # INFO / NOTICE / WARNING / HIGH / CRITICAL
    source: str                # LOCAL / IMPORTED / PORTFOLIO / SYSTEM
    reason: str
    business_impact: str
    recommended_action: str
    expected_urgency: str      # when this requires executive attention
    metric_value: Optional[float]
    threshold_value: Optional[float]
    triggered_at: str          # ISO date

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class WatchlistItem:
    """One executive watchlist entry — one-line headline for daily briefing."""
    item_id: str
    category: str              # INVENTORY / PRICE / TIMING / OPPORTUNITY / RISK / SYSTEM
    headline: str
    detail: str
    days_until_event: Optional[int]
    severity: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ExecutiveMonitoringReport:
    """PSE-7A — Full executive early warning report."""
    run_date: str
    alerts: list
    watchlist: list
    upcoming_procurement_events: list
    upcoming_risk_events: list
    upcoming_savings_opportunities: list
    summary: str
    highest_severity: str
    alert_count_by_severity: dict

    def to_dict(self) -> dict:
        return {
            "run_date":    self.run_date,
            "alerts":      [a.to_dict() if hasattr(a, "to_dict") else a
                            for a in self.alerts],
            "watchlist":   [w.to_dict() if hasattr(w, "to_dict") else w
                            for w in self.watchlist],
            "upcoming_procurement_events":  self.upcoming_procurement_events,
            "upcoming_risk_events":         self.upcoming_risk_events,
            "upcoming_savings_opportunities": self.upcoming_savings_opportunities,
            "summary":               self.summary,
            "highest_severity":      self.highest_severity,
            "alert_count_by_severity": self.alert_count_by_severity,
        }


# ===========================================================================
# Internal alert generators
# ===========================================================================

def _a(alert_id, title, severity, source, reason, business_impact,
       recommended_action, expected_urgency, metric_value=None,
       threshold_value=None, today=None):
    """Shorthand constructor for MonitoringAlert."""
    return MonitoringAlert(
        alert_id=alert_id,
        title=title,
        severity=severity,
        source=source,
        reason=reason,
        business_impact=business_impact,
        recommended_action=recommended_action,
        expected_urgency=expected_urgency,
        metric_value=metric_value,
        threshold_value=threshold_value,
        triggered_at=(today or date.today()).isoformat(),
    )


def _check_inventory_approaching_rop(
    source: str,
    inventory: float,
    rop: float,
    daily_rate: float,
    today: date,
) -> list:
    alerts = []
    sid = source[:3]  # LOC / IMP
    if inventory <= 0 or daily_rate <= 0:
        return alerts

    if inventory <= rop:
        # Already at or below ROP — status engine handles the action; we flag it here
        days_below = round((rop - inventory) / daily_rate, 1)
        alerts.append(_a(
            f"{sid}_ROP_001",
            f"{source} inventory below reorder point",
            "CRITICAL",
            source,
            f"{source} inventory ({inventory:,.0f} t) is {rop - inventory:,.0f} t below "
            f"the approved reorder point of {rop:,.0f} t.  "
            f"This is equivalent to {days_below:.1f} days of unfilled cover.",
            "Procurement pipeline must be active.  Any further delay risks production shutdown.",
            "Confirm an active purchase order is in progress.  "
            "Escalate immediately if no order has been placed.",
            "Immediate",
            metric_value=inventory,
            threshold_value=rop,
            today=today,
        ))
        return alerts

    days_to_rop = (inventory - rop) / daily_rate
    if days_to_rop < _DAYS_TO_ROP_HIGH:
        sev = "HIGH"
        urgency = "Within 1–2 weeks"
    elif days_to_rop < _DAYS_TO_ROP_WARNING:
        sev = "WARNING"
        urgency = "Within 3 weeks"
    elif days_to_rop < _DAYS_TO_ROP_NOTICE:
        sev = "NOTICE"
        urgency = "Within 6 weeks"
    else:
        return alerts

    alerts.append(_a(
        f"{sid}_ROP_{sev[:3]}",
        f"{source} inventory approaching reorder point",
        sev,
        source,
        f"{source} inventory ({inventory:,.0f} t) will reach the reorder point "
        f"({rop:,.0f} t) in approximately {days_to_rop:.0f} days at current "
        f"consumption of {daily_rate:.1f} t/day.",
        "Procurement window is narrowing.  "
        "Delay beyond this point increases shortage risk and reduces negotiating flexibility.",
        f"Review the active procurement plan.  "
        f"Confirm a purchase order will be placed before the reorder threshold is reached.",
        urgency,
        metric_value=round(days_to_rop, 1),
        threshold_value=float(rop),
        today=today,
    ))
    return alerts


def _check_safety_stock_breach(
    source: str,
    inventory: float,
    safety_stock: float,
    daily_rate: float,
    today: date,
) -> list:
    alerts = []
    sid = source[:3]
    if inventory <= 0:
        return alerts

    if inventory < safety_stock:
        days_below = round((safety_stock - inventory) / daily_rate, 1)
        alerts.append(_a(
            f"{sid}_SS_001",
            f"{source} inventory below safety stock",
            "CRITICAL",
            source,
            f"{source} inventory ({inventory:,.0f} t) has breached the approved safety "
            f"stock floor of {safety_stock:,.0f} t — a shortfall of "
            f"{safety_stock - inventory:,.0f} t ({days_below:.1f} days).",
            "Safety stock exists to absorb demand spikes and supply delays.  "
            "Operating below it exposes the mill to production disruption with no buffer.",
            "Prioritise restocking immediately.  "
            "Notify production planning of reduced buffer.  "
            "Escalate to supply chain director.",
            "Immediate",
            metric_value=inventory,
            threshold_value=safety_stock,
            today=today,
        ))
    elif inventory < safety_stock * (1 + _SS_BREACH_BUFFER_PCT):
        alerts.append(_a(
            f"{sid}_SS_HIGH",
            f"{source} inventory near safety stock floor",
            "HIGH",
            source,
            f"{source} inventory ({inventory:,.0f} t) is within 20% of the safety "
            f"stock floor ({safety_stock:,.0f} t).",
            "Continued drawdown without replenishment will breach the safety buffer.",
            "Accelerate procurement.  Verify there are no supplier delays.",
            "Within 1 week",
            metric_value=inventory,
            threshold_value=safety_stock,
            today=today,
        ))
    return alerts


def _check_lead_time_exposure(
    imported_inv: float,
    imported_days_cover: float,
    today: date,
) -> list:
    """Fire if imported inventory cannot cover the full import lead time plus safety days."""
    alerts = []
    required_cover = IMPORTED_LEAD_TIME_DAYS + MIN_STOCK_DAYS
    days_until_must_order = imported_days_cover - required_cover

    if days_until_must_order <= 0:
        alerts.append(_a(
            "IMP_LT_001",
            "Imported lead-time window breached",
            "CRITICAL",
            "IMPORTED",
            f"Imported inventory cover ({imported_days_cover:.0f} days) is below the "
            f"required cover of {required_cover} days (lead time {IMPORTED_LEAD_TIME_DAYS}d "
            f"+ safety {MIN_STOCK_DAYS}d).  An order placed today will arrive after "
            f"stock is exhausted.",
            "Production may face an imported cotton shortage before the next order arrives.",
            "Issue an emergency purchase order immediately.  "
            "Evaluate expedited shipping options.",
            "Immediate",
            metric_value=imported_days_cover,
            threshold_value=float(required_cover),
            today=today,
        ))
    elif days_until_must_order < 14:
        alerts.append(_a(
            "IMP_LT_HIGH",
            "Imported order must be placed within 14 days",
            "HIGH",
            "IMPORTED",
            f"Imported inventory ({imported_inv:,.0f} t, {imported_days_cover:.0f} days) "
            f"requires a purchase order within {days_until_must_order:.0f} days to avoid "
            f"a gap on arrival.",
            "Missing this window will create an imported cotton gap on the production floor.",
            "Confirm the imported purchase order date.  "
            "Do not defer beyond this threshold.",
            "Within 2 weeks",
            metric_value=round(days_until_must_order, 1),
            threshold_value=14.0,
            today=today,
        ))
    elif days_until_must_order < 30:
        alerts.append(_a(
            "IMP_LT_WARN",
            "Imported procurement window is closing",
            "WARNING",
            "IMPORTED",
            f"Imported order must be placed within approximately {days_until_must_order:.0f} "
            f"days to maintain cover through the {IMPORTED_LEAD_TIME_DAYS}-day import lead time.",
            "Delayed ordering will compress the safety buffer on the next import cycle.",
            "Review the imported procurement schedule.  "
            "Ensure supplier capacity and shipping is confirmed.",
            "Within 4 weeks",
            metric_value=round(days_until_must_order, 1),
            threshold_value=30.0,
            today=today,
        ))
    return alerts


def _check_mix_deviation(
    local_inv: float,
    total_inv: float,
    today: date,
) -> list:
    alerts = []
    if total_inv <= 0:
        return alerts

    actual_local_pct  = local_inv / total_inv * 100.0
    actual_imp_pct    = 100.0 - actual_local_pct
    target_local_pct  = LOCAL_MIX_TARGET * 100.0   # 45.0
    target_imp_pct    = IMPORTED_MIX_TARGET * 100.0  # 55.0

    local_dev = actual_local_pct - target_local_pct
    imp_dev   = actual_imp_pct   - target_imp_pct

    for dev, dev_label, target, source_key, sid in [
        (local_dev,  "local",    target_local_pct, "LOCAL",    "LOC"),
        (imp_dev,    "imported", target_imp_pct,   "IMPORTED", "IMP"),
    ]:
        abs_dev = abs(dev)
        if abs_dev < _MIX_DEV_NOTICE:
            continue
        if abs_dev >= _MIX_DEV_HIGH:
            sev, urgency = "HIGH", "This week"
        elif abs_dev >= _MIX_DEV_WARNING:
            sev, urgency = "WARNING", "Within 2 weeks"
        else:
            sev, urgency = "NOTICE", "Within 4 weeks"

        direction = "above" if dev > 0 else "below"
        alerts.append(_a(
            f"{sid}_MIX_{sev[:3]}",
            f"{dev_label.title()} cotton mix drifting {direction} target",
            sev,
            source_key,
            f"Current {dev_label} cotton share is {actual_local_pct if dev_label=='local' else actual_imp_pct:.1f}% "
            f"vs the approved target of {target:.0f}%.  "
            f"Deviation: {abs_dev:.1f} percentage points.",
            f"Mix drift increases dependency on a single source, raising supply concentration risk.  "
            f"It may also violate blending commitments or quality contracts.",
            f"{'Increase' if dev < 0 else 'Reduce'} {dev_label} cotton procurement to rebalance "
            f"toward the {target:.0f}% target over the next procurement cycle.",
            urgency,
            metric_value=round(actual_local_pct if dev_label == "local" else actual_imp_pct, 1),
            threshold_value=target,
            today=today,
        ))
    return alerts


def _check_storage_capacity(
    total_inv: float,
    max_storage: float,
    today: date,
) -> list:
    alerts = []
    if max_storage is None or max_storage <= 0:
        return alerts

    utilisation = total_inv / max_storage
    if utilisation >= _STORAGE_PCT_WARNING:
        sev, urgency = "WARNING", "Immediately"
    elif utilisation >= _STORAGE_PCT_NOTICE:
        sev, urgency = "NOTICE", "This week"
    elif utilisation >= _STORAGE_PCT_INFO:
        sev, urgency = "INFO", "This month"
    else:
        return alerts

    alerts.append(_a(
        f"PORT_STOR_{sev[:3]}",
        f"Storage utilisation at {utilisation*100:.0f}%",
        sev,
        "PORTFOLIO",
        f"Total inventory ({total_inv:,.0f} t) represents {utilisation*100:.1f}% of "
        f"maximum declared storage capacity ({max_storage:,.0f} t).",
        "Storage nearing capacity constrains opportunistic forward buying and "
        "may create logistical bottlenecks during peak production periods.",
        "Review storage utilisation with warehouse team.  "
        "Defer any non-mandatory forward purchases until capacity is cleared.",
        urgency,
        metric_value=round(utilisation * 100, 1),
        threshold_value=_STORAGE_PCT_NOTICE * 100,
        today=today,
    ))
    return alerts


def _check_forecast_confidence(
    exec_report_dict: dict,
    today: date,
) -> list:
    alerts = []
    for source_key in ("local", "imported"):
        dec  = exec_report_dict.get(source_key, {})
        conf = dec.get("confidence", {})
        score = conf.get("score", 100)
        label = conf.get("label", "HIGH")
        sid   = source_key[:3].upper()

        if score < _CONF_SCORE_WARNING:
            sev, urgency = "WARNING", "Review before acting"
        elif score < _CONF_SCORE_NOTICE:
            sev, urgency = "NOTICE", "Monitor closely"
        elif score < _CONF_SCORE_INFO:
            sev, urgency = "INFO", "Watch trend"
        else:
            continue

        alerts.append(_a(
            f"{sid}_CONF_{sev[:3]}",
            f"{source_key.title()} procurement confidence low ({score}/100)",
            sev,
            source_key.upper(),
            f"The decision engine's confidence in the {source_key} recommendation is "
            f"{score}/100 ({label}).  "
            f"Low confidence typically reflects uncertain price signals, "
            f"inventory at a borderline status, or limited forward visibility.",
            "Lower confidence means the recommendation has a higher probability of "
            "being revised if market conditions shift.  "
            "Management should treat the action with more caution.",
            "Request an updated price forecast.  "
            "Consider a smaller initial order with a planned follow-on review "
            "in 7–10 days.",
            urgency,
            metric_value=float(score),
            threshold_value=float(_CONF_SCORE_NOTICE),
            today=today,
        ))
    return alerts


def _check_forecast_direction(
    scenario_report_dict: dict,
    today: date,
) -> list:
    """Alert on conflicting signals between sources or high price volatility."""
    alerts = []
    local_sig  = scenario_report_dict.get("local",    {}).get("price_signal", PRICE_NEUTRAL)
    imp_sig    = scenario_report_dict.get("imported", {}).get("price_signal", PRICE_NEUTRAL)
    local_dp   = scenario_report_dict.get("local",    {}).get("price_delta_pct") or 0.0
    imp_dp     = scenario_report_dict.get("imported", {}).get("price_delta_pct") or 0.0
    local_conf = scenario_report_dict.get("local",    {}).get("price_confidence", "HIGH")
    imp_conf   = scenario_report_dict.get("imported", {}).get("price_confidence", "HIGH")

    # Conflicting directional signals between local and imported
    if local_sig != imp_sig and PRICE_NEUTRAL not in (local_sig, imp_sig):
        alerts.append(_a(
            "PORT_SIG_CONF",
            "Conflicting price signals: local vs imported",
            "NOTICE",
            "PORTFOLIO",
            f"Local cotton price signal is {local_sig} ({local_dp:+.1f}%) while "
            f"imported cotton signal is {imp_sig} ({imp_dp:+.1f}%).  "
            f"The two sources are pointing in opposite directions.",
            "Conflicting signals complicate the optimal buy/defer decision across "
            "the blended portfolio.  One position may partially offset the other.",
            "Seek updated market intelligence for both sources.  "
            "Consider a split-purchase strategy to hedge the directional uncertainty.",
            "Before next order",
            metric_value=abs(local_dp - imp_dp),
            threshold_value=None,
            today=today,
        ))

    # High-magnitude price movement (high volatility)
    for dp, src, conf in [(local_dp, "LOCAL", local_conf), (imp_dp, "IMPORTED", imp_conf)]:
        if abs(dp) >= _PRICE_DELTA_HIGH_VOLATILITY:
            alerts.append(_a(
                f"{src[:3]}_VOL_WARN",
                f"High {src.lower()} price volatility detected ({dp:+.1f}%)",
                "WARNING",
                src,
                f"The {src.lower()} cotton price forecast implies a {dp:+.1f}% "
                f"move from current price.  Forecast confidence: {conf}.",
                "High volatility increases the financial risk of committing to a "
                "large purchase quantity in either direction.  "
                "Actual costs may deviate significantly from model estimates.",
                "Validate the forecast with a second independent source.  "
                "Consider reducing order size and splitting across two procurement dates.",
                "Before committing orders",
                metric_value=round(abs(dp), 1),
                threshold_value=_PRICE_DELTA_HIGH_VOLATILITY,
                today=today,
            ))

    # Low-confidence price signal
    for src, conf, dp in [("LOCAL", local_conf, local_dp), ("IMPORTED", imp_conf, imp_dp)]:
        if conf == "LOW":
            alerts.append(_a(
                f"{src[:3]}_PCONF_INFO",
                f"{src.lower().title()} price confidence is LOW",
                "INFO",
                src,
                f"Price confidence for {src.lower()} cotton is LOW "
                f"(forecast delta {dp:+.1f}%).  "
                "This may reflect insufficient historical data or a very recent market event.",
                "The price-signal component of the recommendation carries higher uncertainty.",
                "Treat price-driven procurement adjustments (forward buy, deferral) with caution.",
                "Next price update",
                metric_value=None,
                threshold_value=None,
                today=today,
            ))
    return alerts


def _check_cost_increase(
    exec_report_dict: dict,
    today: date,
) -> list:
    """Alert when a large cost avoidance opportunity exists (act now to avoid future cost)."""
    alerts = []
    for source_key in ("local", "imported"):
        dec   = exec_report_dict.get(source_key, {})
        fi    = dec.get("expected_cost_impact", {})
        fi_type   = fi.get("impact_type", "NONE")
        avoidance = fi.get("cost_avoidance_usd") or 0.0
        sid   = source_key[:3].upper()

        if fi_type != "COST_AVOIDANCE" or avoidance <= 0:
            continue

        if avoidance >= _COST_INCREASE_HIGH:
            sev, urgency = "HIGH", "Act this week"
        elif avoidance >= _COST_INCREASE_WARNING:
            sev, urgency = "WARNING", "Act within 2 weeks"
        elif avoidance >= _COST_INCREASE_NOTICE:
            sev, urgency = "NOTICE", "Act within 1 month"
        else:
            continue

        alerts.append(_a(
            f"{sid}_COST_{sev[:3]}",
            f"USD {avoidance:,.0f} procurement cost exposure on {source_key} cotton",
            sev,
            source_key.upper(),
            f"The price model projects a cost increase of USD {avoidance:,.0f} on "
            f"{source_key} cotton if procurement is deferred beyond the current recommended "
            f"order date.",
            f"Inaction will result in paying an estimated USD {avoidance:,.0f} more "
            f"to procure the same quantity at the projected higher price.",
            "Follow the active procurement recommendation.  "
            "Confirm order authorisation and issue the purchase order "
            "within the recommended window.",
            urgency,
            metric_value=round(avoidance, 0),
            threshold_value=_COST_INCREASE_NOTICE,
            today=today,
        ))
    return alerts


def _check_saving_opportunity(
    exec_report_dict: dict,
    today: date,
) -> list:
    """Alert when a significant saving opportunity exists from deferral."""
    alerts = []
    for source_key in ("local", "imported"):
        dec   = exec_report_dict.get(source_key, {})
        fi    = dec.get("expected_cost_impact", {})
        fi_type = fi.get("impact_type", "NONE")
        saving  = fi.get("expected_savings_usd") or 0.0
        sid     = source_key[:3].upper()

        if fi_type != "SAVING" or saving <= 0:
            continue

        if saving >= _SAVING_OPP_WARNING:
            sev, urgency = "NOTICE", "Capture before market moves"
        elif saving >= _SAVING_OPP_NOTICE:
            sev, urgency = "NOTICE", "Monitor and confirm"
        elif saving >= _SAVING_OPP_INFO:
            sev, urgency = "INFO", "Track market"
        else:
            continue

        alerts.append(_a(
            f"{sid}_SAV_{sev[:3]}",
            f"USD {saving:,.0f} saving opportunity on {source_key} cotton",
            sev,
            source_key.upper(),
            f"The price model projects that deferring the {source_key} order "
            f"will save approximately USD {saving:,.0f} as prices are forecast to fall.",
            f"Buying now would cost an estimated USD {saving:,.0f} more than "
            f"waiting for the projected price reduction.",
            "Monitor prices closely.  "
            "Defer procurement if inventory position allows and risk is manageable.  "
            "Review the defer-until date in the procurement recommendation.",
            urgency,
            metric_value=round(saving, 0),
            threshold_value=_SAVING_OPP_NOTICE,
            today=today,
        ))
    return alerts


def _check_simulation_outperformance(
    best_sim_score: Optional[int],
    prod_score: Optional[int],
    today: date,
) -> list:
    """Alert if a saved what-if simulation substantially outperforms production."""
    alerts = []
    if best_sim_score is None or prod_score is None:
        return alerts

    delta = best_sim_score - prod_score
    if delta < _SIM_OUTPERFORM_NOTICE:
        return alerts

    sev     = "HIGH" if delta >= _SIM_OUTPERFORM_HIGH else "NOTICE"
    urgency = "Review before next procurement cycle" if sev == "HIGH" else "At next planning session"
    alerts.append(_a(
        "PORT_SIM_OPP",
        f"What-If simulation outperforms production by {delta} pts",
        sev,
        "PORTFOLIO",
        f"A saved What-If simulation achieved an overall strategy score of "
        f"{best_sim_score}/100 vs the current production recommendation of "
        f"{prod_score}/100 — a delta of {delta} points.",
        "There may be an alternative parameter configuration that produces a "
        "materially better procurement outcome under current market conditions.",
        "Open the What-If Lab tab and review the saved simulation.  "
        "If the parameters are realistic, consider updating the procurement plan.",
        urgency,
        metric_value=float(delta),
        threshold_value=float(_SIM_OUTPERFORM_NOTICE),
        today=today,
    ))
    return alerts


def _check_stale_data(
    local_inv: float,
    imported_inv: float,
    total_inv: float,
    today: date,
) -> list:
    """Alert on data quality issues that would corrupt the monitoring output."""
    alerts = []

    # Total inventory is zero
    if total_inv <= 0:
        alerts.append(_a(
            "SYS_DATA_001",
            "Total inventory reads as zero — data may be missing",
            "CRITICAL",
            "SYSTEM",
            "Total inventory is 0 tons.  This is not a valid operational reading.",
            "All procurement recommendations derived from zero inventory will be incorrect.",
            "Refresh the Oracle inventory data feed.  "
            "Do not act on procurement recommendations until the data is validated.",
            "Immediate",
            metric_value=0.0,
            threshold_value=None,
            today=today,
        ))
        return alerts

    # Consistency check: local + imported should sum to total (within 1%)
    computed_total = local_inv + imported_inv
    if abs(computed_total - total_inv) / max(total_inv, 1) > 0.01:
        alerts.append(_a(
            "SYS_DATA_002",
            "Inventory totals are inconsistent",
            "WARNING",
            "SYSTEM",
            f"Local ({local_inv:,.0f} t) + Imported ({imported_inv:,.0f} t) = "
            f"{computed_total:,.0f} t, but total inventory is reported as "
            f"{total_inv:,.0f} t.  Discrepancy: {abs(computed_total - total_inv):,.0f} t.",
            "Inconsistent inventory data may cause incorrect status classification "
            "and flawed procurement recommendations.",
            "Investigate the Oracle data pipeline for a source reconciliation error.  "
            "Do not place orders until the data is validated.",
            "Before acting on recommendations",
            metric_value=round(abs(computed_total - total_inv), 0),
            threshold_value=0.0,
            today=today,
        ))

    # Implausibly large inventory
    if total_inv > 100_000:
        alerts.append(_a(
            "SYS_DATA_003",
            f"Total inventory unusually high ({total_inv:,.0f} t)",
            "WARNING",
            "SYSTEM",
            f"Total inventory of {total_inv:,.0f} t exceeds 100,000 t, which is "
            f"implausibly large for this facility.  This may indicate a data error.",
            "Inflated inventory would suppress procurement urgency and delay necessary orders.",
            "Validate the Oracle data.  "
            "Check for unit conversion errors (e.g., kg reported as t).",
            "Before acting on recommendations",
            metric_value=round(total_inv, 0),
            threshold_value=100_000.0,
            today=today,
        ))

    return alerts


# ===========================================================================
# Watchlist builder
# ===========================================================================

def _build_watchlist(
    alerts: list,
    exec_report_dict: dict,
    scenario_report_dict: dict,
    local_inv: float,
    imported_inv: float,
    total_inv: float,
    today: date,
) -> list:
    """Build the executive watchlist from alerts and upcoming events."""
    watchlist: list[WatchlistItem] = []
    _id = [0]

    def _w(category, headline, detail, days_until_event, severity):
        _id[0] += 1
        return WatchlistItem(
            item_id=f"WL_{_id[0]:03d}",
            category=category,
            headline=headline,
            detail=detail,
            days_until_event=days_until_event,
            severity=severity,
        )

    # ── Inventory status ────────────────────────────────────────────────────
    if local_inv > 0:
        days_l = (local_inv - LOCAL_ROP_TONS) / DAILY_CONSUMPTION_LOCAL
        if days_l > 0:
            watchlist.append(_w(
                "INVENTORY",
                f"Local inventory will reach reorder point in ~{days_l:.0f} days.",
                f"Current: {local_inv:,.0f} t  |  ROP: {LOCAL_ROP_TONS:,.0f} t  |  "
                f"Consumption: {DAILY_CONSUMPTION_LOCAL:.1f} t/day",
                int(round(days_l)),
                "CRITICAL" if days_l < _DAYS_TO_ROP_HIGH else
                "WARNING"  if days_l < _DAYS_TO_ROP_WARNING else
                "NOTICE"   if days_l < _DAYS_TO_ROP_NOTICE  else "INFO",
            ))
        else:
            watchlist.append(_w(
                "INVENTORY",
                f"Local inventory is below reorder point — procurement is overdue.",
                f"Current: {local_inv:,.0f} t  |  ROP: {LOCAL_ROP_TONS:,.0f} t",
                0,
                "CRITICAL",
            ))

    if imported_inv > 0:
        days_i = (imported_inv - IMPORTED_ROP_TONS) / DAILY_CONSUMPTION_IMPORTED
        if days_i > 0:
            watchlist.append(_w(
                "INVENTORY",
                f"Imported inventory will reach reorder point in ~{days_i:.0f} days.",
                f"Current: {imported_inv:,.0f} t  |  ROP: {IMPORTED_ROP_TONS:,.0f} t  |  "
                f"Consumption: {DAILY_CONSUMPTION_IMPORTED:.1f} t/day  |  "
                f"Lead time: {IMPORTED_LEAD_TIME_DAYS} days",
                int(round(days_i)),
                "CRITICAL" if days_i < _DAYS_TO_ROP_HIGH else
                "WARNING"  if days_i < _DAYS_TO_ROP_WARNING else
                "NOTICE"   if days_i < _DAYS_TO_ROP_NOTICE  else "INFO",
            ))
        else:
            watchlist.append(_w(
                "INVENTORY",
                "Imported inventory is below reorder point — procurement is overdue.",
                f"Current: {imported_inv:,.0f} t  |  ROP: {IMPORTED_ROP_TONS:,.0f} t  |  "
                f"Import lead time is {IMPORTED_LEAD_TIME_DAYS} days.",
                0,
                "CRITICAL",
            ))

    # ── Mix position ─────────────────────────────────────────────────────────
    if total_inv > 0:
        actual_local_pct = local_inv / total_inv * 100
        dev = actual_local_pct - LOCAL_MIX_TARGET * 100
        if abs(dev) >= _MIX_DEV_NOTICE:
            direction = "above" if dev > 0 else "below"
            watchlist.append(_w(
                "INVENTORY",
                f"Local cotton mix has drifted {abs(dev):.1f} pp {direction} the "
                f"45% target (current: {actual_local_pct:.1f}%).",
                f"Mix target: Local {LOCAL_MIX_TARGET*100:.0f}% / "
                f"Imported {IMPORTED_MIX_TARGET*100:.0f}%.  "
                f"Current: Local {actual_local_pct:.1f}% / "
                f"Imported {100-actual_local_pct:.1f}%.",
                None,
                "WARNING" if abs(dev) >= _MIX_DEV_WARNING else "NOTICE",
            ))

    # ── Price signals ─────────────────────────────────────────────────────────
    for src_key, label in [("local", "Local"), ("imported", "Imported")]:
        sr_dec = scenario_report_dict.get(src_key, {})
        sig    = sr_dec.get("price_signal", PRICE_NEUTRAL)
        dp     = sr_dec.get("price_delta_pct") or 0.0
        curr_p = sr_dec.get("current_price_usd_per_lb")
        fore_p = sr_dec.get("forecast_price_usd_per_lb")
        if sig != PRICE_NEUTRAL and dp:
            direction = "rising" if sig == PRICE_RISING else "falling"
            curr_str  = f"USD {curr_p:.3f}/lb" if curr_p else "—"
            fore_str  = f"USD {fore_p:.3f}/lb" if fore_p else "—"
            watchlist.append(_w(
                "PRICE",
                f"{label} cotton price is {direction} ({dp:+.1f}%).  "
                f"Current: {curr_str}  |  Forecast: {fore_str}.",
                f"Signal: {sig}  |  Delta: {dp:+.1f}%  |  "
                f"Procurement recommendation adjusted accordingly.",
                None,
                "WARNING" if abs(dp) >= _PRICE_DELTA_HIGH_VOLATILITY else "NOTICE",
            ))

    # ── Upcoming order and arrival dates ──────────────────────────────────────
    for src_key, label in [("local", "Local"), ("imported", "Imported")]:
        dec       = exec_report_dict.get(src_key, {})
        action_c  = dec.get("action_code", "HOLD")
        order_dt  = dec.get("order_date")
        arrival   = dec.get("expected_arrival")
        defer_dt  = dec.get("defer_until")
        qty_now   = dec.get("qty_now_tons", 0)

        if action_c in ("BUY_NOW", "BUY_FORWARD", "BUY_SPLIT") and order_dt:
            try:
                od    = date.fromisoformat(order_dt)
                days  = (od - today).days
                dstr  = f"in {days} days ({od})" if days > 0 else f"today ({od})"
                arr_s = f"  Arrival: {arrival}" if arrival else ""
                watchlist.append(_w(
                    "TIMING",
                    f"{label} purchase order due {dstr} — {qty_now:,.0f} t.",
                    f"Action: {dec.get('action','—')}  |  Qty: {qty_now:,.0f} t"
                    f"{arr_s}",
                    max(0, days),
                    dec.get("urgency", "LOW"),
                ))
            except ValueError:
                pass

        if action_c == "DEFER" and defer_dt:
            watchlist.append(_w(
                "TIMING",
                f"{label} procurement deferred — monitor market until {defer_dt}.",
                f"Defer until: {defer_dt}  |  "
                f"Financial benefit: {dec.get('expected_cost_impact',{}).get('narrative','')}",
                None,
                "INFO",
            ))

    # ── Financial opportunities from HIGH/CRITICAL alerts ─────────────────────
    for alert in alerts:
        if alert.alert_id.endswith("_SAV_NOT") or alert.alert_id.endswith("_SAV_INF"):
            watchlist.append(_w(
                "OPPORTUNITY",
                f"Saving opportunity: {alert.title}",
                alert.reason,
                None,
                alert.severity,
            ))
        if alert.alert_id.endswith("_COST_NOT") or alert.alert_id.endswith("_COST_WAR"):
            watchlist.append(_w(
                "RISK",
                f"Cost exposure: {alert.title}",
                alert.reason,
                None,
                alert.severity,
            ))

    # Sort: soonest upcoming events first, then by severity
    def _sort_key(w: WatchlistItem):
        days = w.days_until_event if w.days_until_event is not None else 999
        sev  = _SEV_RANK.get(w.severity, 4)
        return (sev, days)

    watchlist.sort(key=_sort_key)
    return watchlist


# ===========================================================================
# Upcoming event lists
# ===========================================================================

def _build_upcoming_events(exec_report_dict: dict, today: date) -> list:
    events = []
    for src_key, label in [("local", "LOCAL"), ("imported", "IMPORTED")]:
        dec      = exec_report_dict.get(src_key, {})
        action_c = dec.get("action_code", "HOLD")
        order_dt = dec.get("order_date")
        arrival  = dec.get("expected_arrival")
        qty_now  = dec.get("qty_now_tons", 0)
        urgency  = dec.get("urgency", "LOW")

        if action_c in ("BUY_NOW", "BUY_FORWARD", "BUY_SPLIT") and order_dt:
            try:
                od   = date.fromisoformat(order_dt)
                days = (od - today).days
                events.append({
                    "source":      label,
                    "event_type":  "PURCHASE_ORDER",
                    "date":        order_dt,
                    "days_from_now": days,
                    "quantity_tons": qty_now,
                    "urgency":     urgency,
                    "description": (
                        f"Place {label.lower()} cotton purchase order — "
                        f"{qty_now:,.0f} t"
                    ),
                    "arrival_date": arrival,
                })
            except ValueError:
                pass

    events.sort(key=lambda e: e.get("days_from_now", 9999))
    return events


def _build_risk_events(alerts: list, exec_report_dict: dict, today: date) -> list:
    events = []
    for src_key, label in [("local", "LOCAL"), ("imported", "IMPORTED")]:
        inv_dec = exec_report_dict.get(src_key, {})
        risk    = inv_dec.get("risk", {})
        risk_lv = risk.get("level", "LOW")
        if risk_lv in ("CRITICAL", "HIGH"):
            events.append({
                "source":      label,
                "risk_level":  risk_lv,
                "headline":    risk.get("headline", ""),
                "detail":      risk.get("detail", ""),
                "if_ignored":  risk.get("if_ignored", ""),
                "expected_urgency": inv_dec.get("urgency", "LOW"),
            })

    for a in alerts:
        if _SEV_RANK.get(a.severity, 9) <= 1:  # CRITICAL or HIGH
            events.append({
                "source":          a.source,
                "risk_level":      a.severity,
                "headline":        a.title,
                "detail":          a.reason,
                "if_ignored":      a.business_impact,
                "expected_urgency": a.expected_urgency,
            })

    return events


def _build_savings_opps(
    alerts: list,
    exec_report_dict: dict,
    today: date,
) -> list:
    opps = []
    seen = set()

    for a in alerts:
        if "_SAV_" in a.alert_id and a.alert_id not in seen:
            seen.add(a.alert_id)
            opps.append({
                "source":      a.source,
                "type":        "PRICE_DEFERRAL",
                "amount_usd":  a.metric_value,
                "headline":    a.title,
                "detail":      a.reason,
                "action":      a.recommended_action,
                "urgency":     a.expected_urgency,
            })

    for src_key, label in [("local", "LOCAL"), ("imported", "IMPORTED")]:
        dec  = exec_report_dict.get(src_key, {})
        fi   = dec.get("expected_cost_impact", {})
        fi_t = fi.get("impact_type", "NONE")
        av   = fi.get("cost_avoidance_usd") or 0
        if fi_t == "COST_AVOIDANCE" and av >= _COST_INCREASE_NOTICE:
            opps.append({
                "source":      label,
                "type":        "BUY_NOW_AVOIDANCE",
                "amount_usd":  round(av, 0),
                "headline":    f"USD {av:,.0f} cost avoided by buying {label.lower()} now",
                "detail":      fi.get("narrative", ""),
                "action":      f"Follow the {label.lower()} BUY recommendation.",
                "urgency":     "Act before price rises",
            })

    return opps


# ===========================================================================
# Summary
# ===========================================================================

def _build_summary(
    alerts: list,
    exec_report_dict: dict,
    highest_severity: str,
    today: date,
) -> str:
    n_total    = len(alerts)
    n_critical = sum(1 for a in alerts if a.severity == "CRITICAL")
    n_high     = sum(1 for a in alerts if a.severity == "HIGH")
    port_urg   = exec_report_dict.get("portfolio_urgency", "LOW")

    if n_critical:
        opening = (
            f"CRITICAL monitoring status.  {n_critical} critical alert(s) require "
            f"immediate executive attention."
        )
    elif n_high:
        opening = (
            f"Elevated monitoring status — {n_high} HIGH-severity alert(s) detected."
        )
    elif highest_severity in ("WARNING", "NOTICE"):
        opening = (
            f"Monitoring status: {highest_severity}.  "
            f"{n_total} alert(s) active across the procurement portfolio."
        )
    else:
        opening = "No critical or high-severity alerts.  Portfolio monitoring is in a normal state."

    port_str = (
        f"Portfolio procurement urgency is {port_urg}."
        if port_urg else ""
    )
    guidance = (
        "Review the alert list and watchlist below before authorising any procurement actions."
        if n_total > 0 else
        "Continue to monitor price signals and inventory levels on the standard cycle."
    )
    return f"{opening}  {port_str}  {guidance}".strip()


# ===========================================================================
# Public API
# ===========================================================================

def generate_monitoring_report(
    exec_report_dict: dict,
    scenario_report_dict: dict,
    local_inventory_tons: float,
    imported_inventory_tons: float,
    total_inventory_tons: float,
    today: Optional[date] = None,
    max_storage_tons: Optional[float] = None,
    best_sim_score: Optional[int] = None,
    prod_score: Optional[int] = None,
) -> ExecutiveMonitoringReport:
    """
    Generate an executive monitoring report from existing engine outputs.

    Parameters
    ----------
    exec_report_dict     : ExecutiveReport.to_dict() from PSE-5B
    scenario_report_dict : ScenarioReport.to_dict() from PSE-5A
    local_inventory_tons : current local cotton inventory (tons)
    imported_inventory_tons : current imported cotton inventory (tons)
    total_inventory_tons : total inventory (tons)
    today                : evaluation date (defaults to date.today())
    max_storage_tons     : declared warehouse capacity (optional)
    best_sim_score       : highest scenario score from What-If lab (optional)
    prod_score           : current production scenario score (optional)
    """
    today = today or date.today()

    # ── Run all checkers ─────────────────────────────────────────────────────
    alerts: list[MonitoringAlert] = []

    alerts += _check_stale_data(
        local_inventory_tons, imported_inventory_tons, total_inventory_tons, today)

    # Only continue if data is sane
    if total_inventory_tons > 0:
        alerts += _check_safety_stock_breach(
            "LOCAL", local_inventory_tons, SAFETY_STOCK_LOCAL_TONS,
            DAILY_CONSUMPTION_LOCAL, today)
        alerts += _check_safety_stock_breach(
            "IMPORTED", imported_inventory_tons, SAFETY_STOCK_IMPORTED_TONS,
            DAILY_CONSUMPTION_IMPORTED, today)

        alerts += _check_inventory_approaching_rop(
            "LOCAL", local_inventory_tons, float(LOCAL_ROP_TONS),
            DAILY_CONSUMPTION_LOCAL, today)
        alerts += _check_inventory_approaching_rop(
            "IMPORTED", imported_inventory_tons, float(IMPORTED_ROP_TONS),
            DAILY_CONSUMPTION_IMPORTED, today)

        local_dc   = local_inventory_tons    / DAILY_CONSUMPTION_LOCAL
        imported_dc = imported_inventory_tons / DAILY_CONSUMPTION_IMPORTED
        alerts += _check_lead_time_exposure(
            imported_inventory_tons, imported_dc, today)

        alerts += _check_mix_deviation(
            local_inventory_tons, total_inventory_tons, today)

        if max_storage_tons:
            alerts += _check_storage_capacity(
                total_inventory_tons, max_storage_tons, today)

    alerts += _check_forecast_confidence(exec_report_dict, today)
    alerts += _check_forecast_direction(scenario_report_dict, today)
    alerts += _check_cost_increase(exec_report_dict, today)
    alerts += _check_saving_opportunity(exec_report_dict, today)
    alerts += _check_simulation_outperformance(best_sim_score, prod_score, today)

    # De-duplicate: keep most severe alert per base ID prefix
    seen_prefix: dict[str, int] = {}
    deduped: list[MonitoringAlert] = []
    for a in alerts:
        prefix = a.alert_id.rsplit("_", 1)[0]
        rank   = _SEV_RANK.get(a.severity, 99)
        if prefix not in seen_prefix or rank < seen_prefix[prefix]:
            seen_prefix[prefix] = rank
            deduped = [x for x in deduped if x.alert_id.rsplit("_", 1)[0] != prefix]
            deduped.append(a)

    deduped.sort(key=lambda a: (_SEV_RANK.get(a.severity, 99), a.source, a.alert_id))

    # ── Summary metrics ───────────────────────────────────────────────────────
    count_by_sev: dict[str, int] = {s: 0 for s in _SEV_RANK}
    for a in deduped:
        count_by_sev[a.severity] = count_by_sev.get(a.severity, 0) + 1

    highest_sev = "INFO"
    for sev in ("CRITICAL", "HIGH", "WARNING", "NOTICE", "INFO"):
        if count_by_sev.get(sev, 0) > 0:
            highest_sev = sev
            break

    watchlist = _build_watchlist(
        deduped, exec_report_dict, scenario_report_dict,
        local_inventory_tons, imported_inventory_tons, total_inventory_tons, today,
    )

    return ExecutiveMonitoringReport(
        run_date=today.isoformat(),
        alerts=deduped,
        watchlist=watchlist,
        upcoming_procurement_events=_build_upcoming_events(exec_report_dict, today),
        upcoming_risk_events=_build_risk_events(deduped, exec_report_dict, today),
        upcoming_savings_opportunities=_build_savings_opps(deduped, exec_report_dict, today),
        summary=_build_summary(deduped, exec_report_dict, highest_sev, today),
        highest_severity=highest_sev,
        alert_count_by_severity=count_by_sev,
    )


def run_pse7a(
    workbook_path: Optional[str] = None,
    input_path: Optional[str] = None,
    today: Optional[date] = None,
    max_storage_tons: Optional[float] = None,
    best_sim_score: Optional[int] = None,
    prod_score: Optional[int] = None,
) -> ExecutiveMonitoringReport:
    """
    Convenience runner: runs PSE-5B pipeline then generates the monitoring report.

    Returns ExecutiveMonitoringReport.
    """
    from procurement_orchestrator import run_orchestration
    from procurement_scenario_engine import run_pse5a
    from procurement_decision_engine import generate_executive_report

    today = today or date.today()

    # Single workbook read — passed to run_pse5a via _orch to avoid redundant reads
    orch = run_orchestration(input_path=input_path, workbook_path=workbook_path)
    so   = orch["strategy_output"]

    scenario_report = run_pse5a(
        workbook_path=workbook_path,
        input_path=input_path,
        live_prices=False,
        today=today,
        _orch=orch,
    )

    exec_report = generate_executive_report(
        scenario_report=scenario_report,
        local_status=so.local_status,
        imported_status=so.imported_status,
    )

    return generate_monitoring_report(
        exec_report_dict=exec_report.to_dict(),
        scenario_report_dict=scenario_report.to_dict(),
        local_inventory_tons=float(so.local_inventory_tons),
        imported_inventory_tons=float(so.imported_inventory_tons),
        total_inventory_tons=float(so.total_inventory_tons),
        today=today,
        max_storage_tons=max_storage_tons,
        best_sim_score=best_sim_score,
        prod_score=prod_score,
    )
